version: '3.4'

services:
  balancebeam.identity.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DbConnectionString=Server=SQLServerIdentityDb;Database=BalanceBeam.Identity;User Id=sa;Password=SuperPassword123;Trusted_Connection=False;Encrypt=False
    ports:
      - "5146:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - SQLServerIdentityDb

  SQLServerIdentityDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=SuperPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql